Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Task7.Models;
using Task7.Repository;
using Task7.ViewModel;

namespace Task7.Controllers
{
	public class CoursesController : Controller
	{
		private readonly ICourseRepository _repository;

		public CoursesController(ICourseRepository repository)
		{
			_repository = repository;
		}

		public IActionResult Index()
		{
			var coursesList = _repository.GetAll();
			return View(coursesList);
		}

		public IActionResult Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var course = _repository.GetById(id.Value);
			if (course == null)
			{
				return NotFound();
			}

			return View(course);
		}

		[HttpGet]
		public IActionResult Add()
		{
			var instructors = _repository.GetInstructors();
			var model = new CourseEditViewModel
			{
				Instructors = instructors
			};
			return View(model);
		}

		[HttpPost]
		public IActionResult SaveAdd(CourseEditViewModel model)
		{
			if (!ModelState.IsValid)
			{
				// Repopulate instructors in case of validation failure
				model.Instructors = _repository.GetInstructors();
				return View("Add", model);
			}

			var course = new Course
			{
				Name = model.Name,
				MaximumDegree = model.MaximumDegree,
				MinimumDegree = model.MinimumDegree,
				InstructorId = model.InstructorId
			};

			_repository.Add(course);
			_repository.Save();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
			var course = _repository.GetById(id);
			if (course == null)
			{
				return NotFound();
			}

			var viewModel = new CourseEditViewModel
			{
				Id = course.Id,
				Name = course.Name,
				MaximumDegree = course.MaximumDegree,
				MinimumDegree = course.MinimumDegree,
				InstructorId = course.InstructorId,
				Instructors = _repository.GetInstructors()
			};

			return View(viewModel);
		}

		[HttpPost]
		public IActionResult SaveEdit(CourseEditViewModel model)
		{
			if (ModelState.IsValid)
			{
				var existingCourse = _repository.GetById(model.Id);
				if (existingCourse == null)
				{
					return NotFound();
				}

				existingCourse.Name = model.Name;
				existingCourse.MaximumDegree = model.MaximumDegree;
				existingCourse.MinimumDegree = model.MinimumDegree;
				existingCourse.InstructorId = model.InstructorId;

				_repository.Update(existingCourse);
				_repository.Save();

				return RedirectToAction("Index");
			}

			// If model state is invalid, repopulate the view model and return the view
			model.Instructors = _repository.GetInstructors();
			return View("Edit", model);
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			var courseToDelete = _repository.GetById(id);
			if (courseToDelete == null)
			{
				return NotFound();
			}
			return View(courseToDelete);
		}

		[HttpPost, ActionName("Delete")]
		public IActionResult DeleteConfirmed(int id)
		{
			_repository.Delete(id);
			_repository.Save();
			return RedirectToAction("Index");
		}
	}
}

Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Task7.Models;
using Task7.Repository;

namespace Task7.Controllers
{
	public class DepartmentsController : Controller
	{
		private readonly IDepartmentRepository _repository;

		public DepartmentsController(IDepartmentRepository repository)
		{
			_repository = repository;
		}

		public IActionResult Index()
		{
			var departmentsList = _repository.GetAll();
			return View(departmentsList);
		}

		public IActionResult Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var department = _repository.GetById(id.Value);

			if (department == null)
			{
				return NotFound();
			}

			return View(department);
		}

		[HttpGet]
		public IActionResult Add()
		{
			return View();
		}

		[HttpPost]
		public IActionResult SaveAdd(Department newDepartment)
		{
			if (ModelState.IsValid)
			{
				_repository.Add(newDepartment);
				_repository.Save();
				return RedirectToAction("Index");
			}

			// If model state is invalid, return to the same view with the current data
			return View("Add", newDepartment);
		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
			var department = _repository.GetById(id);
			if (department == null)
			{
				return NotFound();
			}
			return View(department);
		}

		[HttpPost]
		public IActionResult SaveEdit(int id, Department departmentToBeEdited)
		{
			if (id != departmentToBeEdited.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_repository.Update(departmentToBeEdited);
					_repository.Save();
					return RedirectToAction("Index");
				}
				catch (DbUpdateConcurrencyException)
				{
					if (_repository.GetById(id) == null)
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
			}

			// If model state is invalid, return to the same view with the current data
			return View("Edit", departmentToBeEdited);
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			var department = _repository.GetById(id);
			if (department == null)
			{
				return NotFound();
			}
			return View(department);
		}

		[HttpPost, ActionName("Delete")]
		public IActionResult DeleteConfirmed(int id)
		{
			_repository.Delete(id);
			_repository.Save();
			return RedirectToAction("Index");
		}
	}
}

Controllers/InstructorsController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Task7.Models;
using Task7.Models.Repository;
using Task7.Repository;
using Task7.ViewModel;

namespace Task7.Controllers
{
	public class InstructorsController : Controller
	{
		private readonly IInstructorRepository _instructorRepo;

		public InstructorsController(IInstructorRepository instructorRepo)
		{
			_instructorRepo = instructorRepo;
		}

		public IActionResult Index()
		{
			var instructorsList = _instructorRepo.GetAllInstructors().ToList();
			return View(instructorsList);
		}

		public IActionResult Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var instructor = _instructorRepo.GetInstructorById(id.Value);
			if (instructor == null)
			{
				return NotFound();
			}

			return View(instructor);
		}

		[HttpGet]
		public IActionResult Add()
		{
			var departments = _instructorRepo.GetDepartments().ToList(); // Convert IEnumerable to List

			var viewModel = new InstructorWithDept
			{
				DepartmentList = departments
			};

			return View(viewModel);
		}

		[HttpPost]
		public IActionResult SaveAdd(InstructorWithDept model)
		{
			if (!ModelState.IsValid)
			{
				// Re-populate departments in case of validation failure
				model.DepartmentList = _instructorRepo.GetDepartments().ToList(); // Convert IEnumerable to List
				return View("Add", model);
			}

			var newInstructor = new Instructor
			{
				Name = model.Name,
				Address = model.Address,
				Img = model.Img,
				Salary = model.Salary,
				DepartmentId = model.DepartmentId
			};

			_instructorRepo.AddInstructor(newInstructor);
			_instructorRepo.Save();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
			var instructor = _instructorRepo.GetInstructorById(id);
			if (instructor == null)
			{
				return NotFound();
			}

			var departmentList = _instructorRepo.GetDepartments().ToList(); // Convert IEnumerable to List

			var instWithDept = new InstructorWithDept
			{
				Id = instructor.Id,
				Name = instructor.Name,
				Img = instructor.Img,
				Salary = instructor.Salary,
				Address = instructor.Address,
				DepartmentId = instructor.DepartmentId,
				DepartmentList = departmentList
			};

			return View(instWithDept);
		}

		[HttpPost]
		public IActionResult SaveEdit(InstructorWithDept instructorFromRequest)
		{
			if (ModelState.IsValid)
			{
				var instructorFromDB = _instructorRepo.GetInstructorById(instructorFromRequest.Id);
				if (instructorFromDB == null)
				{
					return NotFound();
				}

				instructorFromDB.Name = instructorFromRequest.Name;
				instructorFromDB.Address = instructorFromRequest.Address;
				instructorFromDB.DepartmentId = instructorFromRequest.DepartmentId;
				instructorFromDB.Salary = instructorFromRequest.Salary;
				instructorFromDB.Img = instructorFromRequest.Img;

				_instructorRepo.UpdateInstructor(instructorFromDB);
				_instructorRepo.Save();
				return RedirectToAction("Index");
			}

			instructorFromRequest.DepartmentList = _instructorRepo.GetDepartments().ToList(); // Convert IEnumerable to List
			return View("Edit", instructorFromRequest);
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			var instructorToDelete = _instructorRepo.GetInstructorById(id);
			if (instructorToDelete == null)
			{
				return NotFound();
			}

			return View(instructorToDelete);
		}

		[HttpPost, ActionName("Delete")]
		public IActionResult DeleteConfirmed(int id)
		{
			var instructorToDelete = _instructorRepo.GetInstructorById(id);
			if (instructorToDelete != null)
			{
				_instructorRepo.DeleteInstructor(instructorToDelete);
				_instructorRepo.Save();
			}

			return RedirectToAction("Index");
		}
	}
}

Controllers/TraineesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Task7.Models;
using Task7.Models.Repository;
using Task7.Repository;

namespace Task7.Controllers
{
	public class TraineesController : Controller
	{
		private readonly ITraineeRepository TraineeReposatory;

		public TraineesController(ITraineeRepository traineeRepository)
		{
			TraineeReposatory = traineeRepository;
		}

		public IActionResult Index()
		{
			var traineesList = TraineeReposatory.GetAll();
			return View(traineesList);
		}

		public IActionResult Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var trainee = TraineeReposatory.GetByIDWithCourseResultsAndCourses((int)id); // Updated method

			if (trainee == null)
			{
				return NotFound();
			}

			return View(trainee);
		}

		[HttpGet]
		public IActionResult Add()
		{
			return View();
		}

		[HttpPost]
		public IActionResult SaveAdd(Trainee newTrainee)
		{
			if (ModelState.IsValid)
			{
				TraineeReposatory.Add(newTrainee);
				TraineeReposatory.Save(); // Save the changes
				return RedirectToAction("Index");
			}

			// If model state is invalid, redisplay the form with errors
			return View("Add", newTrainee);
		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
			var trainee = TraineeReposatory.GetByID(id);
			if (trainee == null)
			{
				return NotFound();
			}
			return View(trainee);
		}

		[HttpPost]
		public IActionResult SaveEdit(int id, Trainee traineeToBeEdited)
		{
			if (id != traineeToBeEdited.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					TraineeReposatory.Update(traineeToBeEdited);
					TraineeReposatory.Save(); // Save changes
					return RedirectToAction("Index");
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!TraineeReposatory.GetAll().Any(t => t.Id == id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
			}

			// If model state is invalid, redisplay the form with errors
			return View("Edit", traineeToBeEdited);
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			var traineeToDelete = TraineeReposatory.GetByID(id);
			if (traineeToDelete == null)
			{
				return NotFound();
			}
			return View(traineeToDelete);
		}

		[HttpPost, ActionName("Delete")]
		public IActionResult DeleteConfirmed(int id)
		{
			var traineeToDelete = TraineeReposatory.GetByID(id);
			if (traineeToDelete != null)
			{
				TraineeReposatory.Delete(id);
				TraineeReposatory.Save(); // Save changes
			}

			return RedirectToAction("Index");
		}
	}
}

Views/Shared/_CustomLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - University Portal</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Task7.styles.css" asp-append-version="true" />
	<style>
		/* Navbar styling */
		.navbar {
			box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
		}
		.navbar-brand i {
			color: #4CAF50; /* Green color for icon */
		}
		.navbar-nav .nav-link {
			font-weight: 600;
			transition: color 0.3s;
		}
		.navbar-nav .nav-link:hover {
			color: #4CAF50; /* Hover effect on links */
		}

		/* Main container */
		.container {
			margin-top: 20px;
			padding: 20px;
		}

		/* Footer styling */
		footer {
			background-color: #f8f9fa;
			padding: 20px 0;
			margin-top: 30px;
		}
		footer a {
			text-decoration: none;
			color: #6c757d;
			font-weight: 500;
		}
		footer a:hover {
			color: #000;
		}
		footer .social-icons i {
			font-size: 18px;
			color: #6c757d;
			margin-right: 15px;
			transition: color 0.3s;
		}
		footer .social-icons i:hover {
			color: #4CAF50;
		}

		/* Add subtle animations */
		.fade-in {
			opacity: 0;
			animation: fadeIn 1s forwards;
		}

		@@keyframes fadeIn {
			0% { opacity: 0; }
			100% { opacity: 1; }
		}
	</style>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
			<a class="navbar-brand d-flex align-items-center" asp-controller="Home" asp-action="Index">
				<i class="fa-solid fa-building-columns" style="font-size: 30px;"></i>
				<span class="ms-2">Academic Portal</span>
			</a>

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav ms-auto">
					<li class="nav-item active">
						<a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-controller="Trainees" asp-action="Index">Trainees</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-controller="Instructors" asp-action="Index">Instructors</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-controller="Departments" asp-action="Index">Departments</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-controller="Courses" asp-action="Index">Courses</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-controller="CourseResult" asp-action="Index">Results</a>
					</li>
				</ul>
			</div>
		</nav>
	</header>

	<div class="container fade-in">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted text-center">
		<div class="container">
			<div class="d-flex justify-content-center social-icons">
				<a href="#"><i class="fab fa-facebook-f"></i></a>
				<a href="#"><i class="fab fa-twitter"></i></a>
				<a href="#"><i class="fab fa-linkedin-in"></i></a>
			</div>
			<p class="mt-3">&copy; 2024 - Task7 - <a asp-controller="Home" asp-action="Privacy">Privacy</a></p>
		</div>
	</footer>

	<!-- Script references -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task7</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Task7.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task7</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Task7 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>